import sys
import os
sys.path.insert(0, os.path.dirname(__file__))

from app import app, db, Course

course_data = {
    "data-science-ai": {
        "title": "Data Science & AI Course", "tagline": "Become a Data Scientist - Master Python, ML, Deep Learning & AI",
        "description": "Master Python, Statistics, Machine Learning, Deep Learning & AI with hands-on projects.",
        "overview": "The Data Science & AI training program is designed to make you job-ready. This comprehensive course covers Python programming, statistics, machine learning, deep learning, NLP, and computer vision. You will work on real-world datasets and build 18+ industry projects including predictive models, recommendation systems, image classifiers, and AI chatbots.",
        "key_benefits": "Master Python programming from scratch\nLearn statistics and probability for data science\nBuild machine learning models with scikit-learn\nCreate deep learning models with TensorFlow and Keras\nWork with natural language processing (NLP)\nBuild computer vision applications\nCreate recommendation systems\nDeploy ML models to production\nGet career guidance and interview preparation",
        "eligibility": "<div style='font-family: Inter, Arial, sans-serif; padding: 15px; background: #f8fafc; border-radius: 8px; border: 1px solid #e2e8f0;'><h4 style='color: #1e293b; margin: 0 0 15px 0; font-size: 18px; font-weight: 600;'>Who Should Take This Course?</h4><ul style='margin: 0; padding-left: 20px; color: #475569; line-height: 1.8;'><li style='margin: 8px 0;'><strong style='color: #0066cc;'>Beginners</strong> - No prior programming experience needed</li><li style='margin: 8px 0;'><strong style='color: #0066cc;'>Career Switchers</strong> - Working professionals looking to transition</li><li style='margin: 8px 0;'><strong style='color: #0066cc;'>IT Professionals</strong> - Developers and IT staff wanting new skills</li><li style='margin: 8px 0;'><strong style='color: #0066cc;'>Students & Graduates</strong> - Engineering, Science, Commerce backgrounds</li></ul><p style='margin: 15px 0 0 0; padding: 10px 15px; background: #eff6ff; border-radius: 6px; color: #0066cc; font-weight: 500; font-size: 14px;'>No prior coding experience required! Basic computer knowledge is sufficient.</p></div>",
        "training_schedule": "Weekdays: Mon-Fri (7-10 PM IST)\nWeekends: Sat-Sun (10 AM-2 PM IST)",
        "start_date": "Every Monday", "next_batch": "Starting 1st June 2026",
        "exam_code": "DS-001", "exam_questions": "Maximum 90 Questions", "exam_duration": "90 Minutes",
        "exam_passing_score": "750 (on a scale of 100-900)", "exam_format": "Multiple Choice and Performance-Based",
        "exam_languages": "English, Japanese, Portuguese, Spanish",
        "course_objectives": '["Develop a comprehensive understanding of foundational security concepts","Learn to identify, assess, and mitigate various threats and vulnerabilities","Master the principles and practices of designing a robust security architecture","Gain expertise in day-to-day security operations","Acquire the knowledge and skills required to oversee and manage a security program"]',
        "faq": "Q: Do I need prior coding experience?|No, this course starts from basics.\nQ: What is the course duration?|6 months with weekday and weekend batch options.\nQ: Are there any prerequisites?|Basic mathematical knowledge is sufficient.\nQ: Do you provide job assistance?|Yes, we provide resume building and mock interviews.\nQ: What tools will I learn?|Python, NumPy, Pandas, Scikit-learn, TensorFlow, Keras.",
        "certification": "Yes, Certificate of Completion with unique ID",
        "why_join": "Expert Mentors|Learn from industry experts with 10+ years experience\n18+ Live Projects|Work on real-world projects\nCertificate|Get recognized certificate upon completion\n24/7 Support|Round-the-clock doubt resolution",
        "projects_list": "House Price Prediction\nFraud Detection System\nCustomer Churn Prediction\nMovie Recommendation System\nEmail Spam Classifier\nFace Recognition System\nStock Price Prediction\nSentiment Analysis\nChatbot Development\nCredit Score Prediction",
        "reviews_list": "Amit Sharma | Data Analyst at TCS | This course changed my career completely. The instructors explained complex ML concepts in such a simple way. Within 3 months of completion, I got promoted to Senior Data Analyst with 40% hike!\nPriya Singh | ML Engineer at Flipkart | Best investment I made. The deep learning modules are fantastic! The project on image classification helped me crack my interview at Flipkart. The hands-on approach made learning so easy.\nRajesh Kumar | Data Scientist at Amazon | Got placed within 2 months of completing the course. The curriculum is exactly what companies look for. The mock interviews were extremely helpful. Highly recommended!\nSofia Ahmed | Analytics Manager at Deloitte | Working professional, I took weekend batches. Manageable pace with great content. The NLP project was a game-changer for my career. Now leading a team of 5 analysts.\nVikram Patel | Senior Data Analyst at Microsoft | Started with zero knowledge in Python. The step-by-step approach helped me build strong foundation. The instructors are patient and always available for doubts. Worth every penny!\nAnjali Gupta | Junior Data Scientist at Swiggy | The course content is up-to-date with industry requirements. Learned real-world skills that I apply daily at work. The placement team helped me with resume building and mock interviews.",
        "benefits": "Live Instructor-Led Sessions\nHands-on Projects\nIndustry-Recognized Certificate\nResume Building\n24/7 Support\nLifetime Access\nPlacement Assistance",
        "tools_covered": "Python, NumPy, Pandas, Scikit-learn, TensorFlow, Keras, OpenCV, NLTK, SQL",
        "skills_covered": "Python, Machine Learning, Deep Learning, NLP, Computer Vision, Data Analysis",
        "mode": "Live Online / Self-Paced", "language": "English"
    },
    "cloud-computing-devops": {
        "title": "Cloud Computing & DevOps", "tagline": "Master AWS, Azure, Docker, Kubernetes & CI/CD",
        "description": "Learn AWS, Azure, Docker, Kubernetes & CI/CD pipelines. Deploy real applications to the cloud.",
        "overview": "The Cloud Computing & DevOps training program is designed to make you job-ready in cloud and DevOps roles. This comprehensive course covers AWS, Azure, Docker, Kubernetes, and CI/CD pipelines.",
        "key_benefits": "Master AWS core services\nLearn Azure cloud platform\nDeploy applications with Docker\nOrchestrate containers with Kubernetes\nBuild CI/CD pipelines\nImplement Infrastructure as Code\nMonitor cloud infrastructure",
        "eligibility": "This course is ideal for:\n- IT professionals looking to switch to cloud\n- Developers wanting to learn DevOps\n- System administrators\nBasic understanding of IT concepts is recommended.",
        "training_schedule": "Weekdays: Mon-Fri (8-11 PM IST)\nWeekends: Sat-Sun (9 AM-1 PM IST)",
        "start_date": "Every Monday", "next_batch": "Starting 15th June 2026",
        "exam_code": "CLD-001",
        "faq": "Q: Do I need prior cloud experience?|No, we start from basics.\nQ: What certifications are included?|AWS Solutions Architect prep included.\nQ: How many projects will I work on?|12+ real-world projects.",
        "certification": "Yes, Certificate of Completion with unique ID",
        "why_join": "Expert Mentors|Learn from industry experts\n12+ Live Projects|Work on real cloud projects\nCertificate|Get recognized certificate\nLab Access|Free AWS and Azure lab access",
        "projects_list": "Deploy Scalable Web Application on AWS\nBuild CI/CD Pipeline with Jenkins\nContainerize Application with Docker\nOrchestrate with Kubernetes\nInfrastructure as Code with Terraform",
        "benefits": "Live Instructor-Led Sessions\nHands-on Projects\nIndustry-Recognized Certificate\nResume Building\n24/7 Support\nPlacement Assistance",
        "tools_covered": "AWS, Azure, Docker, Kubernetes, Jenkins, Terraform, Ansible, Git",
        "skills_covered": "AWS, Azure, Docker, Kubernetes, DevOps, CI/CD, Infrastructure as Code",
        "mode": "Live Online / Self-Paced", "language": "English"
    },
    "cyber-security": {
        "title": "Cyber Security Course", "tagline": "Learn Ethical Hacking, Penetration Testing & Network Security",
        "description": "Learn ethical hacking, penetration testing, network security & compliance. Hands-on labs with Kali Linux.",
        "overview": "The Cyber Security training program is designed to make you job-ready in one of the most in-demand fields in tech. This comprehensive course covers ethical hacking, penetration testing, network security, and compliance.",
        "key_benefits": "Master ethical hacking fundamentals\nLearn penetration testing techniques\nUnderstand network security architecture\nWork with Kali Linux and Metasploit\nImplement security controls\nConduct vulnerability assessments\nRespond to security incidents",
        "eligibility": "This course is ideal for:\n- IT professionals looking to switch to security\n- Network administrators\n- System administrators\nBasic understanding of networking is recommended.",
        "training_schedule": "Weekdays: Mon-Fri (7-10 PM IST)\nWeekends: Sat-Sun (10 AM-2 PM IST)",
        "start_date": "Every Monday", "next_batch": "Starting 1st June 2026",
        "exam_code": "CYB-001",
        "faq": "Q: Do I need prior security experience?|No, we start from basics.\nQ: What tools will I learn?|Kali Linux, Metasploit, Burp Suite, Wireshark.\nQ: Are there hands-on labs?|Yes, 15+ hands-on labs.",
        "certification": "Yes, Certificate of Completion with unique ID",
        "why_join": "Expert Mentors|Learn from industry experts\n15+ Live Projects|Work on real security projects\nCertificate|Get recognized certificate\nCEH Prep|Included in curriculum",
        "projects_list": "Network Security Assessment\nPenetration Testing Project\nVulnerability Assessment\nSecurity Incident Response\nWeb Application Security Testing",
        "benefits": "Live Instructor-Led Sessions\nHands-on Projects\nIndustry-Recognized Certificate\nCEH Exam Prep\n24/7 Support\nPlacement Assistance",
        "tools_covered": "Kali Linux, Metasploit, Burp Suite, Wireshark, Nmap, Nessus",
        "skills_covered": "Ethical Hacking, Penetration Testing, Network Security, Vulnerability Assessment",
        "mode": "Live Online / Self-Paced", "language": "English"
    },
    "web-development": {
        "title": "Full Stack Web Development", "tagline": "Master MERN Stack - React, Node.js, MongoDB, Express",
        "description": "Master MERN Stack - React, Node.js, MongoDB, Express. Build 10+ real-world projects.",
        "overview": "The Full Stack Web Development training program is designed to make you job-ready as a full-stack developer. This comprehensive course covers HTML, CSS, JavaScript, React, Node.js, MongoDB, and Express.",
        "key_benefits": "Master HTML, CSS, and JavaScript\nBuild dynamic web applications with React\nCreate server-side applications with Node.js\nWork with MongoDB database\nBuild REST APIs\nImplement authentication and authorization\nDeploy applications to production",
        "eligibility": "This course is ideal for:\n- Beginners with no prior coding experience\n- Anyone interested in web development\n- Designers wanting to learn coding\nNo prior coding experience required.",
        "training_schedule": "Weekdays: Mon-Fri (7-10 PM IST)\nWeekends: Sat-Sun (10 AM-2 PM IST)",
        "start_date": "Every Monday", "next_batch": "Starting 1st June 2026",
        "exam_code": "WEB-001",
        "faq": "Q: Do I need prior coding experience?|No, we start from basics.\nQ: How many projects will I build?|12+ real-world projects.\nQ: What technologies will I learn?|React, Node.js, MongoDB, Express.",
        "certification": "Yes, Certificate of Completion with unique ID",
        "why_join": "Expert Mentors|Learn from industry experts\n12+ Live Projects|Build real applications\nCertificate|Get recognized certificate\nPlacement|Get job assistance",
        "projects_list": "E-commerce Website\nSocial Media Application\nBlog Platform\nTodo Application\nWeather App\nChat Application\nPortfolio Website\nJob Portal",
        "benefits": "Live Instructor-Led Sessions\nHands-on Projects\nIndustry-Recognized Certificate\nResume Building\n24/7 Support\nPlacement Assistance",
        "tools_covered": "HTML, CSS, JavaScript, React, Node.js, MongoDB, Express, Git, Heroku",
        "skills_covered": "Full Stack Development, React, Node.js, MongoDB, REST APIs, Git",
        "mode": "Live Online / Self-Paced", "language": "English"
    },
    "digital-marketing": {
        "title": "Digital Marketing Course", "tagline": "Master SEO, Google Ads, Social Media Marketing & Analytics",
        "description": "Master SEO, Google Ads, Social Media Marketing, Analytics & Content Strategy.",
        "overview": "The Digital Marketing training program is designed to make you job-ready in digital marketing. This comprehensive course covers SEO, Google Ads, Social Media Marketing, Analytics, and Content Strategy.",
        "key_benefits": "Master SEO fundamentals\nLearn Google Ads and PPC\nUnderstand Social Media Marketing\nCreate effective content strategies\nAnalyze with Google Analytics\nImplement email marketing campaigns",
        "eligibility": "This course is ideal for:\n- Marketing professionals\n- Business owners\n- Students\n- Anyone interested in digital marketing\nNo prior experience required.",
        "training_schedule": "Weekdays: Mon-Fri (7-10 PM IST)\nWeekends: Sat-Sun (10 AM-2 PM IST)",
        "start_date": "Every Monday", "next_batch": "Starting 1st June 2026",
        "exam_code": "DM-001",
        "faq": "Q: Do I need prior marketing experience?|No, we start from basics.\nQ: Are Google Ads credits included?|Yes, Rs 10000 Google Ads credit included.\nQ: How many projects will I work on?|6+ real campaigns.",
        "certification": "Yes, Certificate of Completion with unique ID",
        "why_join": "Expert Mentors|Learn from industry experts\nGoogle Ads Credit|Rs 10000 credit included\nCertificate|Get recognized certificate\n6+ Live Projects|Work on real campaigns",
        "projects_list": "SEO Audit Project\nGoogle Ads Campaign\nSocial Media Strategy\nContent Marketing Plan\nEmail Marketing Campaign\nAnalytics Dashboard",
        "benefits": "Live Instructor-Led Sessions\nHands-on Projects\nIndustry-Recognized Certificate\nGoogle Ads Credit\n24/7 Support\nPlacement Assistance",
        "tools_covered": "Google Ads, Google Analytics, Facebook Ads, Instagram, LinkedIn, Twitter, Mailchimp",
        "skills_covered": "SEO, Google Ads, Social Media Marketing, Content Strategy, Analytics, Email Marketing",
        "mode": "Live Online / Self-Paced", "language": "English"
    },
    "business-analytics": {
        "title": "Business Analytics Course", "tagline": "Learn Excel, SQL, Tableau, Power BI & Statistical Analysis",
        "description": "Learn Excel, SQL, Tableau, Power BI & statistical analysis. Work on real business datasets.",
        "overview": "The Business Analytics training program is designed to make you job-ready as a business analyst. This comprehensive course covers Excel, SQL, Tableau, Power BI, and statistical analysis.",
        "key_benefits": "Master Excel advanced functions\nLearn SQL for data analysis\nCreate visualizations with Tableau\nBuild dashboards with Power BI\nUnderstand statistical analysis\nMake data-driven decisions",
        "eligibility": "This course is ideal for:\n- Professionals looking to switch to analytics\n- Business users\n- Students\n- Anyone interested in analytics\nBasic computer knowledge is sufficient.",
        "training_schedule": "Weekdays: Mon-Fri (7-10 PM IST)\nWeekends: Sat-Sun (10 AM-2 PM IST)",
        "start_date": "Every Monday", "next_batch": "Starting 1st June 2026",
        "exam_code": "BA-001",
        "faq": "Q: Do I need prior analytics experience?|No, we start from basics.\nQ: What tools will I learn?|Excel, SQL, Tableau, Power BI.\nQ: How many projects will I work on?|8+ real business projects.",
        "certification": "Yes, Certificate of Completion with unique ID",
        "why_join": "Expert Mentors|Learn from industry experts\n8+ Live Projects|Work on real datasets\nCertificate|Get recognized certificate\nPlacement|Get job assistance",
        "projects_list": "Sales Analytics Dashboard\nCustomer Segmentation Analysis\nFinancial Modeling Project\nHR Analytics Dashboard\nMarketing Campaign Analysis\nSupply Chain Analytics",
        "benefits": "Live Instructor-Led Sessions\nHands-on Projects\nIndustry-Recognized Certificate\nResume Building\n24/7 Support\nPlacement Assistance",
        "tools_covered": "Excel, SQL, Tableau, Power BI, Python, Statistics",
        "skills_covered": "Business Analytics, Data Analysis, Visualization, SQL, Excel, Tableau, Power BI",
        "mode": "Live Online / Self-Paced", "language": "English"
    },
    "ui-ux-design": {
        "title": "UI/UX Design Course", "tagline": "Master Figma, Wireframing, Prototyping & User Research",
        "description": "Master Figma, wireframing, prototyping & user research. Build a professional 10+ piece design portfolio.",
        "overview": "The UI/UX Design training program is designed to make you job-ready as a designer. This comprehensive course covers Figma, wireframing, prototyping, and user research.",
        "key_benefits": "Master Figma design tool\nCreate wireframes and prototypes\nConduct user research\nDesign mobile and web interfaces\nBuild design systems\nCreate a professional portfolio",
        "eligibility": "This course is ideal for:\n- Design enthusiasts\n- Developers wanting to design\n- Students\n- Anyone interested in design\nNo prior design experience required.",
        "training_schedule": "Weekdays: Mon-Fri (7-10 PM IST)\nWeekends: Sat-Sun (10 AM-2 PM IST)",
        "start_date": "Every Monday", "next_batch": "Starting 1st June 2026",
        "exam_code": "UX-001",
        "faq": "Q: Do I need design experience?|No, we start from basics.\nQ: What tools will I learn?|Figma is the primary tool.\nQ: How many projects will I build?|10+ portfolio projects.",
        "certification": "Yes, Certificate of Completion with unique ID",
        "why_join": "Expert Mentors|Learn from industry experts\n10+ Portfolio Projects|Build professional portfolio\nCertificate|Get recognized certificate\nPlacement|Get job assistance",
        "projects_list": "Mobile App Design\nWebsite Design\nE-commerce Design\nDashboard Design\nLanding Page Design\nSocial Media Design\nIcon Set Design\nDesign System",
        "benefits": "Live Instructor-Led Sessions\nHands-on Projects\nIndustry-Recognized Certificate\nProfessional Portfolio\n24/7 Support\nPlacement Assistance",
        "tools_covered": "Figma, Sketch, Adobe XD, Photoshop, Illustrator",
        "skills_covered": "UI Design, UX Design, Figma, Wireframing, Prototyping, User Research",
        "mode": "Live Online / Self-Paced", "language": "English"
    },
    "mobile-app-development": {
        "title": "Mobile App Development", "tagline": "Build iOS & Android Apps with React Native & Flutter",
        "description": "Build iOS & Android apps with React Native & Flutter. Publish to App Store & Google Play.",
        "overview": "The Mobile App Development training program is designed to make you job-ready as a mobile developer. This comprehensive course covers React Native and Flutter.",
        "key_benefits": "Master React Native\nLearn Flutter development\nBuild iOS and Android apps\nImplement Firebase backend\nPublish to App Store and Google Play\nCreate real-time features",
        "eligibility": "This course is ideal for:\n- Developers wanting to build mobile apps\n- Students\n- Anyone interested in mobile development\nBasic programming knowledge is helpful.",
        "training_schedule": "Weekdays: Mon-Fri (7-10 PM IST)\nWeekends: Sat-Sun (10 AM-2 PM IST)",
        "start_date": "Every Monday", "next_batch": "Starting 1st June 2026",
        "exam_code": "MOB-001",
        "faq": "Q: Do I need prior coding experience?|Basic programming knowledge helps.\nQ: What frameworks will I learn?|React Native and Flutter.\nQ: How many apps will I build?|8+ complete mobile applications.",
        "certification": "Yes, Certificate of Completion with unique ID",
        "why_join": "Expert Mentors|Learn from industry experts\n8+ Live Projects|Build real mobile apps\nCertificate|Get recognized certificate\nStore Publishing|Learn to publish to stores",
        "projects_list": "E-commerce Mobile App\nSocial Media App\nChat Application\nFitness Tracking App\nFood Delivery App\nMusic Player App\nNews Reader App",
        "benefits": "Live Instructor-Led Sessions\nHands-on Projects\nIndustry-Recognized Certificate\nStore Publishing\n24/7 Support\nPlacement Assistance",
        "tools_covered": "React Native, Flutter, Firebase, Xcode, Android Studio",
        "skills_covered": "Mobile Development, React Native, Flutter, iOS, Android, Firebase",
        "mode": "Live Online / Self-Paced", "language": "English"
    },
    "aws-solution-architect": {
        "title": "AWS Solutions Architect Certification Training", "tagline": "Master AWS and Get Certified as Solutions Architect",
        "description": "Prepare for AWS Solutions Architect Associate exam. Learn to design distributed systems on AWS.",
        "overview": "The AWS Solutions Architect certification training is designed to make you job-ready for AWS roles. This comprehensive course covers all AWS services and prepares you for the SAA-C03 exam.",
        "key_benefits": "Master AWS core services\nLearn to design scalable architectures\nUnderstand AWS security best practices\nPrepare for SAA-C03 exam\nWork on real AWS projects\nGet career guidance",
        "eligibility": "This course is ideal for:\n- IT professionals\n- Developers\n- System administrators\n- Anyone interested in cloud\nBasic IT knowledge recommended.",
        "training_schedule": "Weekdays: Mon-Fri (8-11 PM IST)\nWeekends: Sat-Sun (9 AM-1 PM IST)",
        "start_date": "Every Monday", "next_batch": "Starting 15th June 2026",
        "exam_code": "AWS-SAA-C03",
        "faq": "Q: Do I need prior AWS experience?|No, we start from basics.\nQ: How many practice exams included?|5 full-length mock exams.\nQ: Is the exam fee included?|No, exam fee is separate.",
        "certification": "Yes, Certificate of Completion + AWS Certification Prep",
        "why_join": "Expert Mentors| AWS certified instructors\n5 Mock Exams|Full-length practice tests\nCertificate|Get recognized certificate\nExam Prep|SAA-C03 exam preparation",
        "projects_list": "Design Highly Available Architecture\nBuild Scalable Web Application\nCreate Serverless Architecture\nDesign Multi-Tier Application\nImplement DR Architecture",
        "benefits": "Live Instructor-Led Sessions\nHands-on Labs\nIndustry-Recognized Certificate\n5 Mock Exams\n24/7 Support\nPlacement Assistance",
        "tools_covered": "AWS Console, AWS CLI, CloudFormation, Terraform",
        "skills_covered": "AWS, Cloud Architecture, EC2, S3, VPC, Lambda, RDS",
        "mode": "Live Online / Self-Paced", "language": "English"
    },
    "python-refresher-ai": {
        "title": "Python Refresher (with AI)", "tagline": "Refresh Your Python Skills and Learn AI Integration",
        "description": "Refresh Python knowledge and learn how to integrate AI capabilities into applications.",
        "overview": "The Python Refresher course is designed for those who know Python but want to brush up their skills and learn AI integration. Perfect for professionals returning to coding.",
        "key_benefits": "Refresh Python fundamentals\nLearn modern Python libraries\nIntegrate AI into applications\nWork with OpenAI APIs\nBuild AI-powered apps\nGet hands-on experience",
        "eligibility": "This course is ideal for:\n- Developers who know Python\n- Professionals returning to coding\n- Those wanting to add AI skills\nBasic Python knowledge required.",
        "training_schedule": "Weekdays: Mon-Fri (7-10 PM IST)\nWeekends: Sat-Sun (10 AM-2 PM IST)",
        "start_date": "Every Monday", "next_batch": "Starting 1st June 2026",
        "exam_code": "PYR-001",
        "faq": "Q: Do I need Python experience?|Yes, basic Python knowledge is required.\nQ: What AI tools will I learn?|OpenAI, Hugging Face, and more.\nQ: How many projects?|5 AI-powered projects.",
        "certification": "Yes, Certificate of Completion with unique ID",
        "why_join": "Expert Mentors|Learn from industry experts\n5 AI Projects|Build AI-powered apps\nCertificate|Get recognized certificate\nLatest Tools|Learn modern AI libraries",
        "projects_list": "AI Chatbot\nImage Generator\nText Summarizer\nSentiment Analyzer\nVoice Assistant",
        "benefits": "Live Instructor-Led Sessions\nHands-on Projects\nIndustry-Recognized Certificate\n24/7 Support\nLifetime Access",
        "tools_covered": "Python, OpenAI, LangChain, Hugging Face, Streamlit",
        "skills_covered": "Python, AI Integration, OpenAI APIs, LLM, Prompt Engineering",
        "mode": "Live Online / Self-Paced", "language": "English"
    },
    "sql-certification": {
        "title": "SQL Certification Course", "tagline": "Master SQL and Become Database Certified Professional",
        "description": "Master SQL from basics to advanced. Prepare for SQL certification exams.",
        "overview": "The SQL Certification course is designed to make you job-ready as a database professional. This comprehensive course covers SQL from basics to advanced concepts.",
        "key_benefits": "Master SQL fundamentals\nLearn advanced SQL queries\nUnderstand database design\nPrepare for SQL certification\nWork with real databases\nGet career guidance",
        "eligibility": "This course is ideal for:\n- Beginners\n- Data analysts\n- Developers\n- Anyone working with data\nNo prior SQL experience required.",
        "training_schedule": "Weekdays: Mon-Fri (7-10 PM IST)\nWeekends: Sat-Sun (10 AM-2 PM IST)",
        "start_date": "Every Monday", "next_batch": "Starting 1st June 2026",
        "exam_code": "SQL-001",
        "faq": "Q: Do I need prior experience?|No, we start from basics.\nQ: Which database will I learn?|MySQL, PostgreSQL, and more.\nQ: How many projects?|10+ real database projects.",
        "certification": "Yes, Certificate of Completion with unique ID",
        "why_join": "Expert Mentors|Learn from industry experts\n10+ Projects|Work on real databases\nCertificate|Get recognized certificate\nCertification Prep|SQL certification prep",
        "projects_list": "Employee Management System\nE-commerce Database\nSchool Management System\nHospital Database\nBank Database Design",
        "benefits": "Live Instructor-Led Sessions\nHands-on Projects\nIndustry-Recognized Certificate\nCertification Prep\n24/7 Support\nPlacement Assistance",
        "tools_covered": "MySQL, PostgreSQL, SQL Server, SQLite, MongoDB",
        "skills_covered": "SQL, Database Design, Query Optimization, Data Modeling",
        "mode": "Live Online / Self-Paced", "language": "English"
    },
    "comptia-network-course": {
        "title": "CompTIA Network+ Course", "tagline": "Get CompTIA Network+ Certified - The Industry Standard",
        "description": "Prepare for CompTIA Network+ certification. Learn networking fundamentals and get certified.",
        "overview": "The CompTIA Network+ certification training is designed to make you job-ready for network administrator roles. This comprehensive course prepares you for the N10-009 exam.",
        "key_benefits": "Master networking fundamentals\nUnderstand network infrastructure\nLearn troubleshooting skills\nPrepare for N10-009 exam\nWork with real network equipment\nGet career guidance",
        "eligibility": "This course is ideal for:\n- IT beginners\n- Network administrators\n- Help desk technicians\n- Anyone interested in networking\nNo prior experience required.",
        "training_schedule": "Weekdays: Mon-Fri (7-10 PM IST)\nWeekends: Sat-Sun (10 AM-2 PM IST)",
        "start_date": "Every Monday", "next_batch": "Starting 1st June 2026",
        "exam_code": "N10-009",
        "faq": "Q: Do I need prior experience?|No, we start from basics.\nQ: How many labs included?|20+ hands-on labs.\nQ: Is exam included?|No, exam fee is separate.",
        "certification": "Yes, Certificate of Completion + CompTIA Network+ Prep",
        "why_join": "Expert Mentors|CompTIA certified instructors\n20+ Labs|Hands-on networking labs\nCertificate|Get recognized certificate\nExam Prep|N10-009 exam preparation",
        "projects_list": "Network Design Project\nSubnetting Exercise\nVLAN Configuration\nRouter and Switch Setup\nTroubleshooting Case Studies",
        "benefits": "Live Instructor-Led Sessions\nHands-on Labs\nIndustry-Recognized Certificate\n20+ Lab Exercises\n24/7 Support\nPlacement Assistance",
        "tools_covered": "Cisco Packet Tracer, GNS3, Wireshark, Nmap",
        "skills_covered": "Networking, Network Security, Troubleshooting, TCP/IP, VLAN, Routing",
        "mode": "Live Online / Self-Paced", "language": "English"
    },
    "microsoft-azure-developer-certification-associate-az-204-training": {
        "title": "Microsoft Azure Developer Certification (AZ-204)", "tagline": "Become Microsoft Certified Azure Developer",
        "description": "Prepare for Microsoft Azure Developer Associate certification (AZ-204). Learn to develop Azure solutions.",
        "overview": "The Microsoft Azure Developer certification training is designed to make you job-ready as an Azure developer. This comprehensive course prepares you for the AZ-204 exam.",
        "key_benefits": "Master Azure development services\nLearn to build cloud solutions\nUnderstand Azure SDKs\nPrepare for AZ-204 exam\nWork on real Azure projects\nGet career guidance",
        "eligibility": "This course is ideal for:\n- Developers\n- IT professionals\n- Cloud enthusiasts\nBasic programming knowledge recommended.",
        "training_schedule": "Weekdays: Mon-Fri (8-11 PM IST)\nWeekends: Sat-Sun (9 AM-1 PM IST)",
        "start_date": "Every Monday", "next_batch": "Starting 15th June 2026",
        "exam_code": "AZ-204",
        "faq": "Q: Do I need prior Azure experience?|Helpful but not required.\nQ: How many projects?|8+ real Azure projects.\nQ: Is exam included?|No, exam fee is separate.",
        "certification": "Yes, Certificate of Completion + AZ-204 Exam Prep",
        "why_join": "Expert Mentors|Microsoft certified instructors\n8+ Projects|Build real Azure solutions\nCertificate|Get recognized certificate\nExam Prep|AZ-204 exam preparation",
        "projects_list": "Azure Functions App\nWeb App Deployment\nAPI Management\nBlob Storage Implementation\nCosmos DB Integration\nAzure AD Implementation",
        "benefits": "Live Instructor-Led Sessions\nHands-on Projects\nIndustry-Recognized Certificate\nExam Prep\n24/7 Support\nPlacement Assistance",
        "tools_covered": "Azure Portal, Visual Studio, VS Code, Azure CLI",
        "skills_covered": "Azure, Cloud Development, Functions, App Service, Cosmos DB, Azure AD",
        "mode": "Live Online / Self-Paced", "language": "English"
    },
    "comptia-security": {
        "title": "CompTIA Security+", "tagline": "Get CompTIA Security+ Certified - Start Your Security Career",
        "description": "Prepare for CompTIA Security+ certification. Learn security fundamentals and get certified.",
        "overview": "The CompTIA Security+ certification training is designed to make you job-ready for security roles. This comprehensive course prepares you for the SY0-701 exam.",
        "key_benefits": "Master security fundamentals\nUnderstand threat landscape\nLearn security technologies\nPrepare for SY0-701 exam\nWork on security projects\nGet career guidance",
        "eligibility": "This course is ideal for:\n- IT beginners\n- Security aspirants\n- Network administrators\n- Anyone interested in security\nNo prior experience required.",
        "training_schedule": "Weekdays: Mon-Fri (7-10 PM IST)\nWeekends: Sat-Sun (10 AM-2 PM IST)",
        "start_date": "Every Monday", "next_batch": "Starting 1st June 2026",
        "exam_code": "SY0-701",
        "faq": "Q: Do I need prior experience?|No, we start from basics.\nQ: How many labs included?|15+ hands-on security labs.\nQ: Is exam included?|No, exam fee is separate.",
        "certification": "Yes, Certificate of Completion + CompTIA Security+ Prep",
        "why_join": "Expert Mentors|CompTIA certified instructors\n15+ Labs|Hands-on security labs\nCertificate|Get recognized certificate\nExam Prep|SY0-701 exam preparation",
        "projects_list": "Security Assessment Project\nVulnerability Scanning\nIncident Response Plan\nSecurity Policy Creation\nPenetration Testing Exercise",
        "benefits": "Live Instructor-Led Sessions\nHands-on Labs\nIndustry-Recognized Certificate\n15+ Lab Exercises\n24/7 Support\nPlacement Assistance",
        "tools_covered": "Kali Linux, Wireshark, Nmap, Nessus, Metasploit",
        "skills_covered": "Security, Network Security, Threat Analysis, Incident Response, Risk Management",
        "mode": "Live Online / Self-Paced", "language": "English"
    },
    "aws-course-certification-training": {
        "title": "AWS Certification Training", "tagline": "Get AWS Certified and Boost Your Career",
        "description": "Comprehensive AWS certification training. Prepare for multiple AWS certifications.",
        "overview": "The AWS Certification training is designed to make you job-ready for AWS roles. This comprehensive course prepares you for various AWS certification exams.",
        "key_benefits": "Master AWS services\nLearn cloud architecture\nUnderstand AWS best practices\nPrepare for AWS exams\nWork on AWS projects\nGet career guidance",
        "eligibility": "This course is ideal for:\n- IT professionals\n- Developers\n- Cloud enthusiasts\n- Anyone interested in AWS\nBasic IT knowledge recommended.",
        "training_schedule": "Weekdays: Mon-Fri (8-11 PM IST)\nWeekends: Sat-Sun (9 AM-1 PM IST)",
        "start_date": "Every Monday", "next_batch": "Starting 15th June 2026",
        "exam_code": "AWS-CERT",
        "faq": "Q: Do I need prior AWS experience?|No, we start from basics.\nQ: Which certifications can I prepare?|Solutions Architect, Developer, SysOps.\nQ: How many projects?|10+ real AWS projects.",
        "certification": "Yes, Certificate of Completion + AWS Certification Prep",
        "why_join": "Expert Mentors|AWS certified instructors\n10+ Projects|Build real AWS projects\nCertificate|Get recognized certificate\nMultiple Certifications|Solutions Architect, Developer, SysOps",
        "projects_list": "EC2 Web Server Setup\nS3 Static Website\nLambda Serverless Function\nDynamoDB Table Design\nCloudFormation Template\nVPC Setup\nLoad Balancer Configuration",
        "benefits": "Live Instructor-Led Sessions\nHands-on Projects\nIndustry-Recognized Certificate\nMultiple Exam Prep\n24/7 Support\nPlacement Assistance",
        "tools_covered": "AWS Console, AWS CLI, CloudWatch, CloudFormation",
        "skills_covered": "AWS, Cloud Computing, Architecture, DevOps, Security",
        "mode": "Live Online / Self-Paced", "language": "English"
    },
    "aws-fundamentals-specialization": {
        "title": "AWS Fundamentals Specialization", "tagline": "Start Your Cloud Journey with AWS Fundamentals",
        "description": "Learn AWS fundamentals. Perfect for beginners starting their cloud journey.",
        "overview": "The AWS Fundamentals specialization is designed for beginners who want to start their cloud journey. This course covers basic AWS services and concepts.",
        "key_benefits": "Understand cloud computing basics\nLearn core AWS services\nGet hands-on experience with AWS\nBuild simple cloud solutions\nPrepare for advanced AWS courses\nGet career guidance",
        "eligibility": "This course is ideal for:\n- Cloud beginners\n- IT students\n- Anyone interested in cloud\nNo prior experience required.",
        "training_schedule": "Weekdays: Mon-Fri (7-10 PM IST)\nWeekends: Sat-Sun (10 AM-2 PM IST)",
        "start_date": "Every Monday", "next_batch": "Starting 1st June 2026",
        "exam_code": "AWS-FUND",
        "faq": "Q: Do I need prior experience?|No, perfect for beginners.\nQ: How many projects?|5 hands-on projects.\nQ: Is this enough for a job?|This is the first step to AWS career.",
        "certification": "Yes, Certificate of Completion",
        "why_join": "Expert Mentors|Experienced instructors\n5 Projects|Hands-on AWS projects\nCertificate|Get recognized certificate\nBeginner Friendly|Start from basics",
        "projects_list": "S3 Bucket Setup\nEC2 Instance Launch\nSimple Web Application\nDatabase Setup\nServerless Function",
        "benefits": "Live Instructor-Led Sessions\nHands-on Projects\nIndustry-Recognized Certificate\nBeginner Friendly\n24/7 Support\nCareer Guidance",
        "tools_covered": "AWS Console, AWS CLI",
        "skills_covered": "AWS, Cloud Basics, EC2, S3, Lambda, IAM",
        "mode": "Live Online / Self-Paced", "language": "English"
    },
    "pmp-certification-training": {
        "title": "PMP Certification Training", "tagline": "Become Project Management Professional - Get PMP Certified",
        "description": "Prepare for PMP certification. Learn project management and get globally recognized certification.",
        "overview": "The PMP Certification training is designed to make you a certified project manager. This comprehensive course prepares you for the PMP exam based on PMBOK 7th edition.",
        "key_benefits": "Master project management fundamentals\nUnderstand PMBOK guide\nLearn agile practices\nPrepare for PMP exam\nLead projects effectively\nGet career guidance",
        "eligibility": "This course is ideal for:\n- Project managers\n- Team leads\n- Aspiring managers\n- Anyone interested in PM\n36 months of project experience required for PMP.",
        "training_schedule": "Weekdays: Mon-Fri (7-10 PM IST)\nWeekends: Sat-Sun (10 AM-2 PM IST)",
        "start_date": "Every Monday", "next_batch": "Starting 1st June 2026",
        "exam_code": "PMP",
        "faq": "Q: Do I need project experience?|Yes, 36 months required for PMP.\nQ: How many mock exams?|5 full-length mock exams.\nQ: Is PMI membership included?|No, but recommended for exam discount.",
        "certification": "Yes, Certificate of Completion + PMP Exam Prep",
        "why_join": "Expert Mentors|PMP certified instructors\n5 Mock Exams|Full-length practice tests\nCertificate|Get recognized certificate\nExam Prep|PMBOK 7th edition based",
        "projects_list": "Project Charter Development\nRisk Management Plan\nSchedule Development\nBudget Planning\nStakeholder Management",
        "benefits": "Live Instructor-Led Sessions\nHands-on Exercises\nIndustry-Recognized Certificate\n5 Mock Exams\n24/7 Support\nPlacement Assistance",
        "tools_covered": "MS Project, Jira, Excel, Trello",
        "skills_covered": "Project Management, Agile, Scrum, Risk Management, Leadership",
        "mode": "Live Online / Self-Paced", "language": "English"
    }
}

def update_courses():
    with app.app_context():
        updated = 0
        for slug, data in course_data.items():
            course = Course.query.filter_by(slug=slug).first()
            if course:
                for key, value in data.items():
                    setattr(course, key, value)
                updated += 1
                print(f"Updated: {course.title}")
        
        db.session.commit()
        print(f"\nTotal courses updated: {updated}")

if __name__ == '__main__':
    update_courses()