import sys
import os
sys.path.insert(0, os.path.dirname(__file__))

from app import app, db, Course

eligibility_data = {
    "cloud-computing-devops": """<div style='font-family: Arial, sans-serif;'><h4 style='color: #1e293b; margin-bottom: 15px;'>Who Should Take This Course?</h4><ul style='list-style: none; padding: 0;'><li style='padding: 10px 15px; margin: 8px 0; background: linear-gradient(135deg, #f8fafc, #f1f5f9); border-left: 4px solid #0066cc; border-radius: 8px;'><strong style='color: #0066cc;'>IT Professionals</strong><br><span style='color: #64748b;'>Looking to switch to cloud computing roles</span></li><li style='padding: 10px 15px; margin: 8px 0; background: linear-gradient(135deg, #f8fafc, #f1f5f9); border-left: 4px solid #7c3aed; border-radius: 8px;'><strong style='color: #7c3aed;'>Developers</strong><br><span style='color: #64748b;'>Wanting to learn DevOps and automation</span></li><li style='padding: 10px 15px; margin: 8px 0; background: linear-gradient(135deg, #f8fafc, #f1f5f9); border-left: 4px solid #10b981; border-radius: 8px;'><strong style='color: #10b981;'>System Administrators</strong><br><span style='color: #64748b;'>Looking to enhance cloud skills</span></li><li style='padding: 10px 15px; margin: 8px 0; background: linear-gradient(135deg, #f8fafc, #f1f5f9); border-left: 4px solid #f59e0b; border-radius: 8px;'><strong style='color: #f59e0b;'>Network Engineers</strong><br><span style='color: #64748b;'>Wanting to transition to cloud roles</span></li></ul><p style='margin-top: 15px; padding: 12px; background: #ecfdf5; border-radius: 8px; color: #065f46;'><strong>Basic understanding of IT concepts recommended!</strong></p></div>""",
    
    "cyber-security": """<div style='font-family: Arial, sans-serif;'><h4 style='color: #1e293b; margin-bottom: 15px;'>Who Should Take This Course?</h4><ul style='list-style: none; padding: 0;'><li style='padding: 10px 15px; margin: 8px 0; background: linear-gradient(135deg, #f8fafc, #f1f5f9); border-left: 4px solid #0066cc; border-radius: 8px;'><strong style='color: #0066cc;'>IT Security Aspirants</strong><br><span style='color: #64748b;'>Want to start career in cyber security</span></li><li style='padding: 10px 15px; margin: 8px 0; background: linear-gradient(135deg, #f8fafc, #f1f5f9); border-left: 4px solid #7c3aed; border-radius: 8px;'><strong style='color: #7c3aed;'>Network Administrators</strong><br><span style='color: #64748b;'>Looking to add security skills</span></li><li style='padding: 10px 15px; margin: 8px 0; background: linear-gradient(135deg, #f8fafc, #f1f5f9); border-left: 4px solid #10b981; border-radius: 8px;'><strong style='color: #10b981;'>System Administrators</strong><br><span style='color: #64748b;'>Want to enhance security knowledge</span></li><li style='padding: 10px 15px; margin: 8px 0; background: linear-gradient(135deg, #f8fafc, #f1f5f9); border-left: 4px solid #f59e0b; border-radius: 8px;'><strong style='color: #f59e0b;'>Bug Bounty Hunters</strong><br><span style='color: #64748b;'>Want to formalize their skills</span></li></ul><p style='margin-top: 15px; padding: 12px; background: #ecfdf5; border-radius: 8px; color: #065f46;'><strong>Basic networking knowledge helpful but not required!</strong></p></div>""",
    
    "web-development": """<div style='font-family: Arial, sans-serif;'><h4 style='color: #1e293b; margin-bottom: 15px;'>Who Should Take This Course?</h4><ul style='list-style: none; padding: 0;'><li style='padding: 10px 15px; margin: 8px 0; background: linear-gradient(135deg, #f8fafc, #f1f5f9); border-left: 4px solid #0066cc; border-radius: 8px;'><strong style='color: #0066cc;'>Complete Beginners</strong><br><span style='color: #64748b;'>No prior coding experience needed</span></li><li style='padding: 10px 15px; margin: 8px 0; background: linear-gradient(135deg, #f8fafc, #f1f5f9); border-left: 4px solid #7c3aed; border-radius: 8px;'><strong style='color: #7c3aed;'>Designers</strong><br><span style='color: #64748b;'>Wanting to learn web development</span></li><li style='padding: 10px 15px; margin: 8px 0; background: linear-gradient(135deg, #f8fafc, #f1f5f9); border-left: 4px solid #10b981; border-radius: 8px;'><strong style='color: #10b981;'>Students</strong><br><span style='color: #64748b;'>Looking for web dev career</span></li><li style='padding: 10px 15px; margin: 8px 0; background: linear-gradient(135deg, #f8fafc, #f1f5f9); border-left: 4px solid #f59e0b; border-radius: 8px;'><strong style='color: #f59e0b;'>Freelancers</strong><br><span style='color: #64748b;'>Want to offer web dev services</span></li></ul><p style='margin-top: 15px; padding: 12px; background: #ecfdf5; border-radius: 8px; color: #065f46;'><strong>No prior experience required! Just passion to learn.</strong></p></div>""",
    
    "digital-marketing": """<div style='font-family: Arial, sans-serif;'><h4 style='color: #1e293b; margin-bottom: 15px;'>Who Should Take This Course?</h4><ul style='list-style: none; padding: 0;'><li style='padding: 10px 15px; margin: 8px 0; background: linear-gradient(135deg, #f8fafc, #f1f5f9); border-left: 4px solid #0066cc; border-radius: 8px;'><strong style='color: #0066cc;'>Marketing Professionals</strong><br><span style='color: #64748b;'>Want to learn digital strategies</span></li><li style='padding: 10px 15px; margin: 8px 0; background: linear-gradient(135deg, #f8fafc, #f1f5f9); border-left: 4px solid #7c3aed; border-radius: 8px;'><strong style='color: #7c3aed;'>Business Owners</strong><br><span style='color: #64748b;'>Want to grow their business online</span></li><li style='padding: 10px 15px; margin: 8px 0; background: linear-gradient(135deg, #f8fafc, #f1f5f9); border-left: 4px solid #10b981; border-radius: 8px;'><strong style='color: #10b981;'>Students</strong><br><span style='color: #64748b;'>Looking for digital marketing career</span></li><li style='padding: 10px 15px; margin: 8px 0; background: linear-gradient(135deg, #f8fafc, #f1f5f9); border-left: 4px solid #f59e0b; border-radius: 8px;'><strong style='color: #f59e0b;'>Content Creators</strong><br><span style='color: #64748b;'>Want to grow their audience</span></li></ul><p style='margin-top: 15px; padding: 12px; background: #ecfdf5; border-radius: 8px; color: #065f46;'><strong>No prior experience needed! Anyone can learn.</strong></p></div>""",
    
    "business-analytics": """<div style='font-family: Arial, sans-serif;'><h4 style='color: #1e293b; margin-bottom: 15px;'>Who Should Take This Course?</h4><ul style='list-style: none; padding: 0;'><li style='padding: 10px 15px; margin: 8px 0; background: linear-gradient(135deg, #f8fafc, #f1f5f9); border-left: 4px solid #0066cc; border-radius: 8px;'><strong style='color: #0066cc;'>Professionals</strong><br><span style='color: #64748b;'>Looking to switch to analytics roles</span></li><li style='padding: 10px 15px; margin: 8px 0; background: linear-gradient(135deg, #f8fafc, #f1f5f9); border-left: 4px solid #7c3aed; border-radius: 8px;'><strong style='color: #7c3aed;'>Business Users</strong><br><span style='color: #64748b;'>Want to make data-driven decisions</span></li><li style='padding: 10px 15px; margin: 8px 0; background: linear-gradient(135deg, #f8fafc, #f1f5f9); border-left: 4px solid #10b981; border-radius: 8px;'><strong style='color: #10b981;'>Students</strong><br><span style='color: #64748b;'>Looking for analytics career</span></li><li style='padding: 10px 15px; margin: 8px 0; background: linear-gradient(135deg, #f8fafc, #f1f5f9); border-left: 4px solid #f59e0b; border-radius: 8px;'><strong style='color: #f59e0b;'>Managers</strong><br><span style='color: #64748b;'>Want to leverage data for business</span></li></ul><p style='margin-top: 15px; padding: 12px; background: #ecfdf5; border-radius: 8px; color: #065f46;'><strong>Basic computer knowledge is sufficient!</strong></p></div>""",
    
    "ui-ux-design": """<div style='font-family: Arial, sans-serif;'><h4 style='color: #1e293b; margin-bottom: 15px;'>Who Should Take This Course?</h4><ul style='list-style: none; padding: 0;'><li style='padding: 10px 15px; margin: 8px 0; background: linear-gradient(135deg, #f8fafc, #f1f5f9); border-left: 4px solid #0066cc; border-radius: 8px;'><strong style='color: #0066cc;'>Design Enthusiasts</strong><br><span style='color: #64748b;'>Passionate about design</span></li><li style='padding: 10px 15px; margin: 8px 0; background: linear-gradient(135deg, #f8fafc, #f1f5f9); border-left: 4px solid #7c3aed; border-radius: 8px;'><strong style='color: #7c3aed;'>Developers</strong><br><span style='color: #64748b;'>Wanting to add design skills</span></li><li style='padding: 10px 15px; margin: 8px 0; background: linear-gradient(135deg, #f8fafc, #f1f5f9); border-left: 4px solid #10b981; border-radius: 8px;'><strong style='color: #10b981;'>Students</strong><br><span style='color: #64748b;'>Looking for design career</span></li><li style='padding: 10px 15px; margin: 8px 0; background: linear-gradient(135deg, #f8fafc, #f1f5f9); border-left: 4px solid #f59e0b; border-radius: 8px;'><strong style='color: #f59e0b;'>Graphic Designers</strong><br><span style='color: #64748b;'>Want to transition to UI/UX</span></li></ul><p style='margin-top: 15px; padding: 12px; background: #ecfdf5; border-radius: 8px; color: #065f46;'><strong>No prior design experience required!</strong></p></div>""",
    
    "mobile-app-development": """<div style='font-family: Arial, sans-serif;'><h4 style='color: #1e293b; margin-bottom: 15px;'>Who Should Take This Course?</h4><ul style='list-style: none; padding: 0;'><li style='padding: 10px 15px; margin: 8px 0; background: linear-gradient(135deg, #f8fafc, #f1f5f9); border-left: 4px solid #0066cc; border-radius: 8px;'><strong style='color: #0066cc;'>Developers</strong><br><span style='color: #64748b;'>Want to build mobile apps</span></li><li style='padding: 10px 15px; margin: 8px 0; background: linear-gradient(135deg, #f8fafc, #f1f5f9); border-left: 4px solid #7c3aed; border-radius: 8px;'><strong style='color: #7c3aed;}>Students</strong><br><span style='color: #64748b;'>Looking for mobile development career</span></li><li style='padding: 10px 15px; margin: 8px 0; background: linear-gradient(135deg, #f8fafc, #f1f5f9); border-left: 4px solid #10b981; border-radius: 8px;'><strong style='color: #10b981;'>Entrepreneurs</strong><br><span style='color: #64748b;'>Want to build their own app</span></li><li style='padding: 10px 15px; margin: 8px 0; background: linear-gradient(135deg, #f8fafc, #f1f5f9); border-left: 4px solid #f59e0b; border-radius: 8px;'><strong style='color: #f59e0b;}>Web Developers</strong><br><span style='color: #64748b;'>Want to expand to mobile</span></li></ul><p style='margin-top: 15px; padding: 12px; background: #ecfdf5; border-radius: 8px; color: #065f46;'><strong>Basic programming knowledge helpful!</strong></p></div>"""
}

review_data = {
    "cloud-computing-devops": """Rahul Verma | Cloud Engineer at Accenture | This course helped me transition from IT support to cloud engineering. The AWS and Azure labs were excellent. Got my first cloud job within 4 months!\nKavita Singh | DevOps Engineer at Infosys | The CI/CD pipeline project was amazing. Learned Jenkins, Docker, and Kubernetes in depth. My manager was impressed with my skills.\nSanjay Joshi | Solutions Architect at Wipro | Comprehensive course covering all major cloud platforms. The Terraform project was exactly what I needed for my role.\nPooja Nair | System Administrator at HCL | As a sysadmin, this course helped me understand cloud infrastructure. The Kubernetes modules are top-notch. Highly recommended!\nArjun Reddy | Junior Cloud Developer | Started from zero cloud knowledge. The step-by-step approach and hands-on labs made learning easy. Now working as a cloud developer.""",
    
    "cyber-security": """Vikram Singh | Security Analyst at Cognizant | The ethical hacking modules exceeded my expectations. The penetration testing labs gave me real-world experience. Cleared my CEH exam on first attempt!\nAnita Desai | SOC Analyst at Deloitte | Perfect course for beginners. The Kali Linux and Metasploit training was comprehensive. Now working in a security operations center.\nRohit Mehta | Junior Penetration Tester | The hands-on labs were incredibly useful. Learned to find vulnerabilities and write reports. The instructor explained complex topics simply.\nNeha Sharma | Information Security Engineer | Career switch from IT support to security. The network security concepts were well explained. Great learning experience!\nAditya Patel | Security Consultant | The course covered everything from basics to advanced. The incident response module was particularly helpful for my job.""",
    
    "web-development": """Arun Kumar | Junior Web Developer at startup | Started with zero coding knowledge. Now I can build complete web applications. The MERN stack training is excellent!\nDivya Reddy | Frontend Developer at Paytm | The React modules are comprehensive. Built my portfolio with 5 projects during the course. Got hired within a month of completion!\nMohit Sharma | Full Stack Developer | The project-based approach is brilliant. Built an e-commerce site from scratch. The instructors are very supportive.\nSneha Gupta | Web Developer at Byju's | Perfect for beginners. HTML, CSS, JS taught very well. The transition to React was smooth. Highly recommend!\nRavi Patel | Freelance Developer | Learned enough to start my own freelance business. The deployment section was very practical. Great course!""",
    
    "digital-marketing": """Priya Iyer | Digital Marketing Manager | The SEO training is excellent. My website traffic increased 300% after implementing what I learned. Worth every penny!\nRahul Sharma | Social Media Manager | The social media modules are up-to-date with latest trends. The Google Ads certification prep was very helpful.\nAnkita Singh | Content Strategist | The content marketing strategy module changed my approach. Now managing content for 5 major brands.\nVikram Bajaj | Performance Marketer | The Google Ads course is practical. Within 2 months, I reduced cost per lead by 40% for my client.\nSonam Gupta | Email Marketing Specialist | The email marketing campaign project was excellent. Learned automation and segmentation in depth.""",
    
    "business-analytics": """Amitabh Roy | Business Analyst at HSBC | The SQL and Tableau training is excellent. The real-world business cases helped me understand how to apply analytics at work.\nRiya Kapoor | Data Analyst at Goldman Sachs | Transitioned from marketing to analytics. The Python for analytics modules were perfect. Got 50% salary hike!\nSuresh Nair | Senior Analyst at Flipkart | The Power BI dashboard project is amazing. Learned to create interactive dashboards that impressed my leadership.\nKavita Mishra | BI Developer | The course covered all major analytics tools. The instructors are industry experts who share real scenarios.\nDeepak Verma | Analytics Lead | The statistical analysis module was very thorough. Now leading a team of 8 analysts. Best investment!""",
    
    "ui-ux-design": """Anjali Sen | UI Designer at Adobe | The Figma training is comprehensive. Built a portfolio of 12 projects during the course. Got hired at my dream company!\nRohit Khanna | UX Researcher at Google | The user research modules are excellent. Learned to conduct interviews, usability tests, and create research reports.\nMeera Singh | Product Designer at Amazon | The design system project was brilliant. Now I can create consistent designs across products. Highly recommend!\nAryan Sharma | Freelance Designer | Built my design business after this course. The portfolio review sessions helped me refine my work. Great instructors!\nTina Dutta | Junior UX Designer | Perfect for career switchers. The step-by-step approach made learning design easy. Now working at a startup.""",
    
    "mobile-app-development": """Kunal Shah | Mobile Developer at Swiggy | The React Native course is excellent. Built 3 apps during training. The Firebase integration was very practical!\nAnisha Reddy | iOS Developer at Apple | Transitioned from web to mobile development. The Swift and Flutter modules were comprehensive. Love my new job!\nAditya Kumar | Android Developer at Google Play | The Kotlin and Jetpack Compose training is up-to-date. Built apps that are now on Play Store!\nSofia Ahmed | Cross-Platform Developer | Learned both React Native and Flutter. The project-based approach gave me real app development experience.\nRaj Malhotra | Mobile App Entrepreneur | Built my startup app during this course. The publishing guide helped me launch on both stores. Amazing course!"""
}

def update_eligibility_reviews():
    with app.app_context():
        for slug, eligibility in eligibility_data.items():
            course = Course.query.filter_by(slug=slug).first()
            if course:
                course.eligibility = eligibility
        
        for slug, reviews in review_data.items():
            course = Course.query.filter_by(slug=slug).first()
            if course:
                course.reviews_list = reviews
        
        db.session.commit()
        print("Eligibility and Reviews updated successfully!")

if __name__ == '__main__':
    update_eligibility_reviews()