import sys
import os
sys.path.insert(0, os.path.dirname(__file__))

from app import app, db, Course

simple_eligibility = {
    "data-science-ai": "<div style='font-family: Inter, Arial, sans-serif; padding: 15px; background: #f8fafc; border-radius: 8px; border: 1px solid #e2e8f0;'><h4 style='color: #1e293b; margin: 0 0 15px 0; font-size: 18px; font-weight: 600;'>Who Should Take This Course?</h4><ul style='margin: 0; padding-left: 20px; color: #475569; line-height: 1.8;'><li style='margin: 8px 0;'><strong style='color: #0066cc;'>Beginners</strong> - No prior programming experience needed</li><li style='margin: 8px 0;'><strong style='color: #0066cc;'>Career Switchers</strong> - Working professionals looking to transition</li><li style='margin: 8px 0;'><strong style='color: #0066cc;'>IT Professionals</strong> - Developers and IT staff wanting new skills</li><li style='margin: 8px 0;'><strong style='color: #0066cc;'>Students & Graduates</strong> - Engineering, Science, Commerce backgrounds</li></ul><p style='margin: 15px 0 0 0; padding: 10px 15px; background: #eff6ff; border-radius: 6px; color: #0066cc; font-weight: 500; font-size: 14px;'>No prior coding experience required! Basic computer knowledge is sufficient.</p></div>",
    
    "cloud-computing-devops": "<div style='font-family: Inter, Arial, sans-serif; padding: 15px; background: #f8fafc; border-radius: 8px; border: 1px solid #e2e8f0;'><h4 style='color: #1e293b; margin: 0 0 15px 0; font-size: 18px; font-weight: 600;'>Who Should Take This Course?</h4><ul style='margin: 0; padding-left: 20px; color: #475569; line-height: 1.8;'><li style='margin: 8px 0;'><strong style='color: #0066cc;'>IT Professionals</strong> - Looking to switch to cloud computing roles</li><li style='margin: 8px 0;'><strong style='color: #0066cc;'>Developers</strong> - Wanting to learn DevOps and automation</li><li style='margin: 8px 0;'><strong style='color: #0066cc;'>System Administrators</strong> - Looking to enhance cloud skills</li><li style='margin: 8px 0;'><strong style='color: #0066cc;'>Network Engineers</strong> - Wanting to transition to cloud roles</li></ul><p style='margin: 15px 0 0 0; padding: 10px 15px; background: #eff6ff; border-radius: 6px; color: #0066cc; font-weight: 500; font-size: 14px;'>Basic understanding of IT concepts recommended!</p></div>",
    
    "cyber-security": "<div style='font-family: Inter, Arial, sans-serif; padding: 15px; background: #f8fafc; border-radius: 8px; border: 1px solid #e2e8f0;'><h4 style='color: #1e293b; margin: 0 0 15px 0; font-size: 18px; font-weight: 600;'>Who Should Take This Course?</h4><ul style='margin: 0; padding-left: 20px; color: #475569; line-height: 1.8;'><li style='margin: 8px 0;'><strong style='color: #0066cc;'>IT Security Aspirants</strong> - Want to start career in cyber security</li><li style='margin: 8px 0;'><strong style='color: #0066cc;'>Network Administrators</strong> - Looking to add security skills</li><li style='margin: 8px 0;'><strong style='color: #0066cc;'>System Administrators</strong> - Want to enhance security knowledge</li><li style='margin: 8px 0;'><strong style='color: #0066cc;'>IT Professionals</strong> - Looking for security career</li></ul><p style='margin: 15px 0 0 0; padding: 10px 15px; background: #eff6ff; border-radius: 6px; color: #0066cc; font-weight: 500; font-size: 14px;'>Basic networking knowledge helpful but not required!</p></div>",
    
    "web-development": "<div style='font-family: Inter, Arial, sans-serif; padding: 15px; background: #f8fafc; border-radius: 8px; border: 1px solid #e2e8f0;'><h4 style='color: #1e293b; margin: 0 0 15px 0; font-size: 18px; font-weight: 600;'>Who Should Take This Course?</h4><ul style='margin: 0; padding-left: 20px; color: #475569; line-height: 1.8;'><li style='margin: 8px 0;'><strong style='color: #0066cc;'>Complete Beginners</strong> - No prior coding experience needed</li><li style='margin: 8px 0;'><strong style='color: #0066cc;'>Designers</strong> - Wanting to learn web development</li><li style='margin: 8px 0;'><strong style='color: #0066cc;'>Students</strong> - Looking for web dev career</li><li style='margin: 8px 0;'><strong style='color: #0066cc;'>Freelancers</strong> - Want to offer web dev services</li></ul><p style='margin: 15px 0 0 0; padding: 10px 15px; background: #eff6ff; border-radius: 6px; color: #0066cc; font-weight: 500; font-size: 14px;'>No prior experience required! Just passion to learn.</p></div>",
    
    "digital-marketing": "<div style='font-family: Inter, Arial, sans-serif; padding: 15px; background: #f8fafc; border-radius: 8px; border: 1px solid #e2e8f0;'><h4 style='color: #1e293b; margin: 0 0 15px 0; font-size: 18px; font-weight: 600;'>Who Should Take This Course?</h4><ul style='margin: 0; padding-left: 20px; color: #475569; line-height: 1.8;'><li style='margin: 8px 0;'><strong style='color: #0066cc;'>Marketing Professionals</strong> - Want to learn digital strategies</li><li style='margin: 8px 0;'><strong style='color: #0066cc;'>Business Owners</strong> - Want to grow their business online</li><li style='margin: 8px 0;'><strong style='color: #0066cc;'>Students</strong> - Looking for digital marketing career</li><li style='margin: 8px 0;'><strong style='color: #0066cc;'>Content Creators</strong> - Want to grow their audience</li></ul><p style='margin: 15px 0 0 0; padding: 10px 15px; background: #eff6ff; border-radius: 6px; color: #0066cc; font-weight: 500; font-size: 14px;'>No prior experience needed! Anyone can learn.</p></div>",
    
    "business-analytics": "<div style='font-family: Inter, Arial, sans-serif; padding: 15px; background: #f8fafc; border-radius: 8px; border: 1px solid #e2e8f0;'><h4 style='color: #1e293b; margin: 0 0 15px 0; font-size: 18px; font-weight: 600;'>Who Should Take This Course?</h4><ul style='margin: 0; padding-left: 20px; color: #475569; line-height: 1.8;'><li style='margin: 8px 0;'><strong style='color: #0066cc;'>Professionals</strong> - Looking to switch to analytics roles</li><li style='margin: 8px 0;'><strong style='color: #0066cc;'>Business Users</strong> - Want to make data-driven decisions</li><li style='margin: 8px 0;'><strong style='color: #0066cc;'>Students</strong> - Looking for analytics career</li><li style='margin: 8px 0;'><strong style='color: #0066cc;'>Managers</strong> - Want to leverage data for business</li></ul><p style='margin: 15px 0 0 0; padding: 10px 15px; background: #eff6ff; border-radius: 6px; color: #0066cc; font-weight: 500; font-size: 14px;'>Basic computer knowledge is sufficient!</p></div>",
    
    "ui-ux-design": "<div style='font-family: Inter, Arial, sans-serif; padding: 15px; background: #f8fafc; border-radius: 8px; border: 1px solid #e2e8f0;'><h4 style='color: #1e293b; margin: 0 0 15px 0; font-size: 18px; font-weight: 600;'>Who Should Take This Course?</h4><ul style='margin: 0; padding-left: 20px; color: #475569; line-height: 1.8;'><li style='margin: 8px 0;'><strong style='color: #0066cc;'>Design Enthusiasts</strong> - Passionate about design</li><li style='margin: 8px 0;'><strong style='color: #0066cc;'>Developers</strong> - Wanting to add design skills</li><li style='margin: 8px 0;'><strong style='color: #0066cc;'>Students</strong> - Looking for design career</li><li style='margin: 8px 0;'><strong style='color: #0066cc;'>Graphic Designers</strong> - Want to transition to UI/UX</li></ul><p style='margin: 15px 0 0 0; padding: 10px 15px; background: #eff6ff; border-radius: 6px; color: #0066cc; font-weight: 500; font-size: 14px;'>No prior design experience required!</p></div>",
    
    "mobile-app-development": "<div style='font-family: Inter, Arial, sans-serif; padding: 15px; background: #f8fafc; border-radius: 8px; border: 1px solid #e2e8f0;'><h4 style='color: #1e293b; margin: 0 0 15px 0; font-size: 18px; font-weight: 600;'>Who Should Take This Course?</h4><ul style='margin: 0; padding-left: 20px; color: #475569; line-height: 1.8;'><li style='margin: 8px 0;'><strong style='color: #0066cc;'>Developers</strong> - Want to build mobile apps</li><li style='margin: 8px 0;'><strong style='color: #0066cc;'>Students</strong> - Looking for mobile development career</li><li style='margin: 8px 0;'><strong style='color: #0066cc;'>Entrepreneurs</strong> - Want to build their own app</li><li style='margin: 8px 0;'><strong style='color: #0066cc;'>Web Developers</strong> - Want to expand to mobile</li></ul><p style='margin: 15px 0 0 0; padding: 10px 15px; background: #eff6ff; border-radius: 6px; color: #0066cc; font-weight: 500; font-size: 14px;'>Basic programming knowledge helpful!</p></div>"
}

def update():
    with app.app_context():
        for slug, elig in simple_eligibility.items():
            course = Course.query.filter_by(slug=slug).first()
            if course:
                course.eligibility = elig
        db.session.commit()
        print("Simple eligibility updated for all courses!")

if __name__ == '__main__':
    update()